name: Pre-Commit Checks

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  pre-commit:
    name: Run Pre-Commit Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies avoiding changes in the lock file
        run: pnpm install --frozen-lockfile

      - name: Run Pre-Commit Checks
        run: npx @biomejs/biome check --write --no-errors-on-unmatched --colors=off {staged_files}